### ISSUE TITLE
Infobip throws `409` error if we try to cancel already sent SMSs 

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/Miracle-Feet#55]
## Describe the bug
See issue #32 for the latest specs. 
On `2021-04-14` we scheduled the SMS `casting_intro-5-2925e24d-5d75-4387-8216-11edb2aeacf6`
See run: https://www.openfn.org/projects/pdbznd/runs/rzd759jr

Later on `2021-05-04` we try to disable the SMS `casting_intro-5-2925e24d-5d75-4387-8216-11edb2aeacf6`
See run: https://www.openfn.org/projects/pdbznd/runs/r9wxn97n

However, by now this SMS has already be sent, which is why I think Infobip is throwing this error: 
```
{
  "statusCode": 409,
  "body": {
    "requestError": {
      "serviceException": {
        "messageId": "CONFLICT",
        "text": "Bulk with id casting_intro-5-2925e24d-5d75-4387-8216-11edb2aeacf6 cannot be set to status CANCELED"
      }
    }
  },
  ```

### expression.js
schedule_sms.js

### state.json
See LP for Infobip portal
You can re-run this again to try to reproduce: https://www.openfn.org/projects/pdbznd/runs/r9wxn97n

## Expected behavior
When we GET sms from Infobip to check for existing messages using `bulkId`... is it possible to check the SMS `status`? This way, if the sms is already `sent`... then no need to try to cancel.

**Comment by ritazagoni** [comment]
Resolved with https://www.openfn.org/projects/pdbznd/runs/ryaed757

**Comment by aleksa-krolls** [comment]
@lakhassane @ritazagoni I'm not sure this issue has been resolved. See run failure from this morning: https://www.openfn.org/projects/pdbznd/runs/rn5783py

**Comment by lakhassane** [comment]
@ritazagoni corrected also for rescheduling

**Comment by ritazagoni** [comment]
hey @lakhassane thanks. we're almost there. out of the 3 recent failures, 2 pass and 1 still fails with `conflict` from Infobip.
Resolved: 
1. message https://www.openfn.org/projects/pdbznd/messages/mn57kbzq (successful [run](https://www.openfn.org/projects/pdbznd/runs/rwapj6m8) )
2. message https://www.openfn.org/projects/pdbznd/messages/mwbg9ga5 (successful [run](https://www.openfn.org/projects/pdbznd/messages/mwbg9ga5) )

*Still fails*:
message https://www.openfn.org/projects/pdbznd/messages/mwbg9ga5, failed [run](https://www.openfn.org/projects/pdbznd/runs/rrk3e9wn)

**Comment by lakhassane** [comment]
@ritazagoni corrections done!

**Comment by ritazagoni** [comment]
Resolved, successful run: https://www.openfn.org/projects/pdbznd/runs/rzdkdw6m
